### PR TITLE
test parallel build

### PR DESCRIPTION
**Pull request by danieleades**
this PR is an attempt to test that this sphinx extension works correctly for parallel builds.

This doesn't work right now, as evidenced by the fact that there is no increase in coverage when compared to the `main` branch (the 'merge' method is not currently executed during testing - https://github.com/danieleades/sphinx-graph/blob/60ea5ac5f203dec3216d537c0d0cf10139176588/src/sphinx_graph/vertex/state.py#L53-L61)

### CODE REVIEW

**Comment by danieleades** [comment]
@AA-turner do you know of any way to make this work?

**Comment by danieleades** [comment]
@picnixz since you're refactoring the sphinx testing framework, maybe you can comment on this?

Is it possible to force parallel build in testing so as to test the 'merge' event of a sphinx extension?

**Comment by picnixz** [comment]
Yes, currently you need to pass `parallel=4` for instance to assume a 4 jobs build.

Note that parallel builds are still disabled if you have less than 5 documents to build IIRC. There is a test with parallel=2 iirc so you can check that one.

In the future, I plan to allow to force parallel jobs or to warn users that the number of documents are not enough for parallelization.

**Comment by danieleades** [comment]
> Yes, currently you need to pass `parallel=4` for instance to assume a 4 jobs build.
> 
> Note that parallel builds are still disabled if you have less than 5 documents to build IIRC. There is a test with parallel=2 iirc so you can check that one.
> 
> In the future, I plan to allow to force parallel jobs or to warn users that the number of documents are not enough for parallelization.

that seems to have done it!

thank you so much, i've had this ticket sitting open for months

**Comment by picnixz** [comment]
I've been fighting the test suite so much that I know it well.

**Pull request merged**
